# Generated by Django 4.2.5 on 2023-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
    ]
