# Generated by Django 4.2.5 on 2023-09-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_clientes_dni_alter_clientes_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoria',
            new_name='bodega',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='producto',
            new_name='etiqueta',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='categoria',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='precio',
            new_name='legajo',
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='producto',
            new_name='nombre',
        ),
    ]
